version: 2
jobs:
  build:
    working_directory: ~/page
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
  deploy:
    working_directory: ~/page
    docker:
      - image: ansible/ansible:ubuntu1604
    steps:
      - run:
          name: Install System Packages
          # pip issue :( https://github.com/pyenv/pyenv/issues/1141#issuecomment-381421570
          command: python -m pip install --force-reinstall pip && pip install ansible && pip install boto && pip install boto3 && pip install botocore && pip install awscli --upgrade

      - checkout
      - restore_cache:
          key: page-{{ .Branch }}-{{ checksum "./ansible/playbook.yml" }}-v1
      - run: ansible-playbook ansible/playbook.yml
      - save_cache:
          key: page-{{ .Branch }}-{{ checksum "./ansible/playbook.yml" }}-v1
          paths:
            - '/root/.ansible/roles'

      # @TODO Deploy to AWS here...

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
