version: 2
jobs:
  build:
    working_directory: ~/page
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
  deploy:
    working_directory: ~/page
    docker:
      - image: ansible/ansible:ubuntu1604
    steps:
      - run:
          name: Install System Packages
          command: pip install --upgrade pip && pip install ansible

      - checkout
      - restore_cache:
          key: page-{{ .Branch }}-{{ checksum "./ansible/requirements.yml" }}-v1
      - run: ansible-galaxy install -r ansible/requirements.yml
      - save_cache:
          key: page-{{ .Branch }}-{{ checksum "./ansible/requirements.yml" }}-v1
          paths:
            - '/root/.ansible/roles'

      # @TODO Deploy to AWS here...

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
