- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False
  
  tasks:
    - name: Install AWSCLI
      pip: name=awscli state=present
    - name: Create acm cert request
      shell: >
        aws acm request-certificate --domain-name jmtestpage4.jannes.mingram.net
        --validation-method DNS
        --subject-alternative-names www.jmtestpage4.jannes.mingram.net
        --idempotency-token jmtestpage4
        --region us-east-1
      register: cert
    - name: Safe cert details
      set_fact:
        acm_item_cert_arn: "{{ (cert.stdout|from_json).CertificateArn }}"
    - name: Create an Bucket
      s3_bucket:
        name: jmtestpage4
        region: eu-central-1
      register: bucket_details
    - name: Configure bucket as website
      s3_website :
        name: jmtestpage4
        region: eu-central-1
        error_key: index.html
        state: present
    - name: Upload files
      s3_sync:
        bucket: jmtestpage4
        region: eu-central-1
        file_root: ../target/
        permission: public-read
        cache_control: "public, max-age=31536000"
        file_change_strategy: checksum
        mode: push
    - name: obtain all facts for a single ACM certificate
      aws_acm_facts:
        domain_name: "jmtestpage4.jannes.mingram.net"
        region: us-east-1
      register: cert_details
    - name: Creat DNS entry 1
      uri:
        url: https://dns.api.gandi.net/api/v5/domains/mingram.net/records
        method: POST
        body: "{
             \"rrset_name\": \"{{ cert_details.certificates[0].domain_validation_options[0].resource_record.name }}\",
             \"rrset_type\": \"{{ cert_details.certificates[0].domain_validation_options[0].resource_record.type }}\",
             \"rrset_values\": [\"{{ cert_details.certificates[0].domain_validation_options[0].resource_record.value }}\"],
             \"rrset_ttl\": 3600
             }"
        status_code: 201, 200
        body_format: json
        headers:
          Content-Type: "application/json"
          X-Api-Key: "{{ lookup('env','GANDI') }}"
    - name: Creat DNS entry 2
      uri:
        url: https://dns.api.gandi.net/api/v5/domains/mingram.net/records
        method: POST
        body: "{
             \"rrset_name\": \"{{ cert_details.certificates[0].domain_validation_options[1].resource_record.name }}\",
             \"rrset_type\": \"{{ cert_details.certificates[0].domain_validation_options[1].resource_record.type }}\",
             \"rrset_values\": [\"{{ cert_details.certificates[0].domain_validation_options[1].resource_record.value }}\"],
             \"rrset_ttl\": 3600
             }"
        status_code: 201, 200
        body_format: json
        headers:
          Content-Type: "application/json"
          X-Api-Key: "{{ lookup('env','GANDI') }}"    
    - name: Details about cert-id
      debug:
        msg: "{{ (cert.stdout|from_json).CertificateArn }}"
    - name: Details about bucket
      debug:
        var: bucket_details
    - name: Setup cloudfront
      cloudfront_distribution:
        state: present
        enabled: no
        origins: 
          - s3_origin_access_identity_enabled: yes
            domain_name: jmtestpage4.s3.amazonaws.com
            id: 'jmtestpage4'
        aliases: [ 'jmtestpage4.jannes.mingram.net', 'www.jmtestpage4.jannes.mingram.net' ]
        viewer_certificate:
          acm_certificate_arn: "{{ (cert.stdout|from_json).CertificateArn }}"
          certificate : "{{ (cert.stdout|from_json).CertificateArn }}"
          certificate_source: acm
          ssl_support_method: sni-only
          minimum_protocol_version: "TLSv1.2_2018"
        tags:
          Name: example distribution
          Project: example project
          Priority: '1'
        
        
