- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False
  
  tasks:
    - name: Create an Bucket
      s3_bucket:
        name: jmtestpage2
        region: eu-central-1
    - name: Configure bucket as website
      s3_website :
        name: jmtestpage2
        region: eu-central-1
        error_key: index.html
        


