- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False
  
  tasks:
    - name: Create an Bucket
      s3:
        name: jmtestpage2
        region: eu-central-1
        mode: create
        permission: public-read
        


